#!/usr/bin/with-contenv bash

echo "*** VSCODE Installer ***"
echo "Checking if vscode is installed"

if ! code -v &> /dev/null; then 
    echo "VSCODE not installed, installing now..." 
    if ! curl --version &> /dev/null; then
        echo "curl not installed, installing now..." 
        apt-get install curl -y
    fi
    curl -sSL https://packages.microsoft.com/keys/microsoft.asc -o microsoft.asc
    apt-key add microsoft.asc
    rm microsoft.asc
    echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"  | tee /etc/apt/sources.list.d/vscode.list
    apt update
    apt install -y code
else
    echo "vscode already installed, skipping!"
fi
